stages:
  - build
  - test

job_build:
  stage: build
  script:
    - echo "Building the project"
  rules:
    - if: '$CI_COMMIT_BRANCH == "BE/develop"'

job_test:
  stage: test
  script:
    - echo "Running tests"
  rules:
    - if: '$CI_COMMIT_BRANCH == "BE/develop"'
